# compose.yml
services:
  # spring-boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    # JPA 구동 실패 시
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}
      SPRING_DATASOURCE_USERNAME: ${PGUSER}
      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}
    env_file: .env
    networks:
      - mon-net
    volumes:
      - log-data:/app/logs
    # Dockerfile -> app (작업 디렉토리) -> jar -> app/logs

  loki:
    image: grafana/loki:latest
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml:ro
      # ro는 권한 문제가 없기 때문에 바인딩 마운트 사용에 문제가 없는데
      # 계속 바뀌는 파일들은 네임드 볼륨으로 하시는게 낫다
    command:
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - mon-net

  #  promtail:
  #    image: grafana/promtail:latest
  #    restart: always
  #    volumes:
  #      # app -> promtail (pull) -> loki (push)
  #      - log-data:/var/log/app:ro
  #      - ./config/promtail.yml:/etc/promtail/config.yml:ro
  #    command:
  #      - -config.file=/etc/promtail/config.yml
  #    depends_on:
  #      - loki
  #      - app
  #    networks:
  #      - mon-net
  alloy:
    image: grafana/alloy:latest
    restart: always
    volumes:
      # app -> alloy (pull) -> loki (push)
      - log-data:/var/log/app:ro
      # Alloy configuration
      #      - ./config/alloy-local.alloy:/etc/alloy/config.alloy:ro
      - ./config/alloy-cloud.alloy:/etc/alloy/config.alloy:ro
      # File read position / Alloy state
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    depends_on:
      - loki
      - app
    networks:
      - mon-net

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - mon-net
    # loki, prometheus -> grafana
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      #      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus-cloud.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    networks:
      - mon-net
    depends_on:
      - app

  alertmanager:
    image: prom/alertmanager:latest
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - mon-net

networks:
  mon-net:

volumes:
  log-data:
  alloy-data:
  grafana-data: