# application.yaml
spring:
  application:
    name: complex-back
  profiles:
    active: dev,db
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]